name: with_camera
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  camera: ^0.11.0+2
  path: ^1.9.0
  provider: ^6.1.2
  permission_handler: ^11.3.1
  geolocator: ^13.0.1
  http: ^1.2.2
  image: ^4.3.0
  archive: ^3.6.1
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

